wardCoveTimes = {
    "Ward Cove": 0,
    "Dock 2": 25,
    "Dock 1": 25,
    "Dock 3": 25,
    "Dock 4": 25,
    "Lumberjack": 25,
    "George Inlet": 50,
    "Cannery": 60,
    "Rainforest": 40,
    "Cape Fox Lodge": 30,
    "Saxmon": 35,
    "Disco": 25,
    "Taquan": 20,
    "Jeep Base": 7,
    "Harriot Hunt": 30,
    "White River": 45,
    "Adventure Carts": 25,
    "Knudson": 30,
    "Clover Pass": 40,
    "Totem Byte": 25,
    "Lighthouse": 5,
    "Cambria": 17
}

dock4Times = {
    "Dock 4": 0,
    "Dock 2": 7,
    "Dock 1": 7,
    "Dock 3": 7,
    "Ward Cove": wardCoveTimes["Dock 4"],
    "Lumberjack": 8,
    "George Inlet": 45,
    "Cannery": 50,
    "Rainforest": 30,
    "Cape Fox Lodge": 20,
    "Saxmon": 30,
    "Disco": 8,
    "Taquan": 10,
    "Jeep Base": 20,
    "Harriot Hunt": 45,
    "White River": 55,
    "Adventure Carts": 35,
    "Knudson": 40,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 20,
    "Cambria": 12
}

dock3Times = {
    "Dock 3": 0,
    "Dock 2": 5,
    "Dock 1": 5,
    "Dock 4": dock4Times["Dock 3"],
    "Ward Cove": wardCoveTimes["Dock 3"],
    "Lumberjack": 5,
    "George Inlet": 40,
    "Cannery": 50,
    "Rainforest": 25,
    "Cape Fox Lodge": 15,
    "Saxmon": 25,
    "Disco": 5,
    "Taquan": 10,
    "Jeep Base": 25,
    "Harriot Hunt": 50,
    "White River": 55,
    "Adventure Carts": 40,
    "Knudson": 45,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 20,
    "Cambria": 15
}

dock2Times = {
    "Dock 2": 0,
    "Dock 4": dock4Times["Dock 2"],
    "Dock 1": 5,
    "Dock 3": dock3Times["Dock 2"],
    "Ward Cove": wardCoveTimes["Dock 2"],
    "Lumberjack": 5,
    "George Inlet": 40,
    "Cannery": 50,
    "Rainforest": 25,
    "Cape Fox Lodge": 15,
    "Saxmon": 25,
    "Disco": 5,
    "Taquan": 10,
    "Jeep Base": 25,
    "Harriot Hunt": 50,
    "White River": 55,
    "Adventure Carts": 40,
    "Knudson": 45,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 25,
    "Cambria": 15
}

dock1Times = {
    "Dock 1": 0,
    "Dock 4": dock4Times["Dock 1"],
    "Dock 2": dock2Times["Dock 1"],
    "Dock 3": dock3Times["Dock 1"],
    "Ward Cove": wardCoveTimes["Dock 1"],
    "Lumberjack": 5,
    "George Inlet": 40,
    "Cannery": 50,
    "Rainforest": 25,
    "Cape Fox Lodge": 15,
    "Saxmon": 25,
    "Disco": 5,
    "Taquan": 10,
    "Jeep Base": 25,
    "Harriot Hunt": 50,
    "White River": 55,
    "Adventure Carts": 40,
    "Knudson": 45,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 25,
    "Cambria": 15
}

lumberjackTimes = {
    "Dock 1": dock1Times["Lumberjack"],
    "Dock 4": dock4Times["Lumberjack"],
    "Dock 2": dock2Times["Lumberjack"],
    "Dock 3": dock3Times["Lumberjack"],
    "Ward Cove": wardCoveTimes["Lumberjack"],
    "Lumberjack": 0,
    "George Inlet": 40,
    "Cannery": 50,
    "Rainforest": 25,
    "Cape Fox Lodge": 15,
    "Saxmon": 25,
    "Disco": 5,
    "Taquan": 10,
    "Jeep Base": 25,
    "Harriot Hunt": 50,
    "White River": 55,
    "Adventure Carts": 40,
    "Knudson": 45,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 25,
    "Cambria": 15
}

georgeInletTimes = {
    "Dock 1": dock1Times["George Inlet"],
    "Dock 4": dock4Times["George Inlet"],
    "Dock 2": dock2Times["George Inlet"],
    "Dock 3": dock3Times["George Inlet"],
    "Ward Cove": wardCoveTimes["George Inlet"],
    "Lumberjack": lumberjackTimes["George Inlet"],
    "George Inlet": 0,
    "Cannery": 10,
    "Rainforest": 20,
    "Cape Fox Lodge": 45,
    "Saxmon": 25,
    "Disco": 40,
    "Taquan": 45,
    "Jeep Base": 50,
    "Harriot Hunt": 70,
    "White River": 85,
    "Adventure Carts": 70,
    "Knudson": 70,
    "Clover Pass": 70,
    "Totem Byte": 60,
    "Lighthouse": 50,
    "Cambria": 50
}

canneryTimes = {
    "Dock 1": dock1Times["Cannery"],
    "Dock 4": dock4Times["Cannery"],
    "Dock 2": dock2Times["Cannery"],
    "Dock 3": dock3Times["Cannery"],
    "Ward Cove": wardCoveTimes["Cannery"],
    "Lumberjack": lumberjackTimes["Cannery"],
    "George Inlet": georgeInletTimes["Cannery"],
    "Cannery": 0,
    "Rainforest": 25,
    "Cape Fox Lodge": 45,
    "Saxmon": 30,
    "Disco": 50,
    "Taquan": 55,
    "Jeep Base": 60,
    "Harriot Hunt": 80,
    "White River": 95,
    "Adventure Carts": 80,
    "Knudson": 80,
    "Clover Pass": 80,
    "Totem Byte": 70,
    "Lighthouse": 60,
    "Cambria": 55
}

rainforestTimes = {
    "Dock 1": dock1Times["Rainforest"],
    "Dock 4": dock4Times["Rainforest"],
    "Dock 2": dock2Times["Rainforest"],
    "Dock 3": dock3Times["Rainforest"],
    "Ward Cove": wardCoveTimes["Rainforest"],
    "Lumberjack": lumberjackTimes["Rainforest"],
    "George Inlet": georgeInletTimes["Rainforest"],
    "Cannery": canneryTimes["Rainforest"],
    "Rainforest": 0,
    "Cape Fox Lodge": 40,
    "Saxmon": 25,
    "Disco": 25,
    "Taquan": 30,
    "Jeep Base": 40,
    "Harriot Hunt": 65,
    "White River": 70,
    "Adventure Carts": 60,
    "Knudson": 70,
    "Clover Pass": 75,
    "Totem Byte": 60,
    "Lighthouse": 40,
    "Cambria": 35
}