wardCoveTimes = {
    "Ward Cove": 0,
    "Dock 2": 25,
    "Dock 1": 25,
    "Dock 3": 25,
    "Dock 4": 25,
    "Lumberjack": 25,
    "George Inlet": 50,
    "Cannery": 60,
    "Rainforest": 40,
    "Cape Fox Lodge": 30,
    "Saxmon": 35,
    "Disco": 25,
    "Taquan": 20,
    "Jeep Base": 7,
    "Harriot Hunt": 30,
    "White River": 45,
    "Adventure Carts": 25,
    "Knudson": 30,
    "Clover Pass": 40,
    "Totem Byte": 25,
    "Lighthouse": 5,
    "Cambria": 17
}

dock4Times = {
    "Dock 4": 0,
    "Dock 2": 7,
    "Dock 1": 7,
    "Dock 3": 7,
    "Ward Cove": wardCoveTimes["Dock 4"],
    "Lumberjack": 8,
    "George Inlet": 45,
    "Cannery": 50,
    "Rainforest": 30,
    "Cape Fox Lodge": 20,
    "Saxmon": 30,
    "Disco": 8,
    "Taquan": 10,
    "Jeep Base": 20,
    "Harriot Hunt": 45,
    "White River": 55,
    "Adventure Carts": 35,
    "Knudson": 40,
    "Clover Pass": 45,
    "Totem Byte": 35,
    "Lighthouse": 20,
    "Cambria": 12
}